apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
    run: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
   metadata:
    labels:
      app: frontend
   spec:
    containers:
    - image: 172.31.1.107:5000/mgsgoms/flask:${BUILD_NUMBER}
      name: frontend
